### ISSUE TITLE
Error when running python webUI.py

### ISSUE THREAD

**Issue by Crazy-CYZ** [williamyang1991/FRESCO#10]
(diffusers) PS D:\FRESCO> python webUI.py
safety_checker\model.safetensors not found
Loading pipeline components...:   0%|                                                            | 0/7 [00:00<?, ?it/s]D:\miniconda3\envs\diffusers\lib\site-packages\torch\_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
Loading pipeline components...: 100%|████████████████████████████████████████████████████| 7/7 [00:04<00:00,  1.55it/s]
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
safety_checker\model.safetensors not found
Loading pipeline components...:   0%|                                                            | 0/7 [00:00<?, ?it/s]D:\miniconda3\envs\diffusers\lib\site-packages\torch\_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
Loading pipeline components...:  29%|██████████████▊                                     | 2/7 [00:03<00:08,  1.67s/it]D:\miniconda3\envs\diffusers\lib\site-packages\transformers\models\clip\feature_extraction_clip.py:28: FutureWarning: The class CLIPFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use CLIPImageProcessor instead.
  warnings.warn(
Loading pipeline components...: 100%|████████████████████████████████████████████████████| 7/7 [00:04<00:00,  1.54it/s]
Traceback (most recent call last):
  File "D:\miniconda3\envs\diffusers\lib\site-packages\gradio\queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "D:\miniconda3\envs\diffusers\lib\site-packages\gradio\route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\miniconda3\envs\diffusers\lib\site-packages\gradio\blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "D:\miniconda3\envs\diffusers\lib\site-packages\gradio\blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\miniconda3\envs\diffusers\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "D:\miniconda3\envs\diffusers\lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "D:\miniconda3\envs\diffusers\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "D:\miniconda3\envs\diffusers\lib\site-packages\gradio\utils.py", line 650, in wrapper
    response = f(*args, **kwargs)
  File "D:\miniconda3\envs\diffusers\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "webUI.py", line 159, in process
    keypath = process1(*args)
  File "D:\miniconda3\envs\diffusers\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "webUI.py", line 172, in process1
    global_state.update_sd_model(sd_model)
  File "webUI.py", line 149, in update_sd_model
    self.pipe.scheduler = DDPMScheduler.from_config(pipe.scheduler.config)
NameError: name 'pipe' is not defined

**Comment by williamyang1991** [comment]
Thank you. The bug is fixed
https://github.com/williamyang1991/FRESCO/pull/11/files
