### ISSUE TITLE
Error in saving the video

### ISSUE THREAD

**Issue by karthikg-09** [williamyang1991/FRESCO#12]
Getting error on selecting Run All
using the given example dog video

```100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 24/24 [00:25<00:00,  1.07s/it]
python video_blend.py output/dog --key keys --key_ind 0 11 23 49 72 99  --output output/dog/blend.mp4 --fps 24 --n_proc 4 -ps
/workspace/FRESCO/venv/lib/python3.10/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3526.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/workspace/FRESCO/venv/lib/python3.10/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3526.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/workspace/FRESCO/venv/lib/python3.10/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3526.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/workspace/FRESCO/venv/lib/python3.10/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3526.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
[ WARN:0@76.176] global loadsave.cpp:248 findDecoder imread_('output/dog/out_0/0001.jpg'): can't open/read file: check file path/integrity
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/workspace/FRESCO/video_blend.py", line 111, in process_sequences
    process_one_sequence(i, video_sequence)
  File "/workspace/FRESCO/video_blend.py", line 98, in process_one_sequence
    cmd += ' ' + g.get_cmd(j, w)
  File "/workspace/FRESCO/./src/ebsynth/blender/guide.py", line 96, in get_cmd
    warped_img = flow_calc.warp(prev_img, self.flows[i - 1],
  File "/workspace/FRESCO/./src/ebsynth/flow/flow_utils.py", line 230, in warp
    if len(img.shape) == 2:
AttributeError: 'NoneType' object has no attribute 'shape'
[ WARN:0@99.287] global loadsave.cpp:248 findDecoder imread_('output/dog/out_49/0050.jpg'): can't open/read file: check file path/integrity
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/workspace/FRESCO/video_blend.py", line 111, in process_sequences
    process_one_sequence(i, video_sequence)
  File "/workspace/FRESCO/video_blend.py", line 98, in process_one_sequence
    cmd += ' ' + g.get_cmd(j, w)
  File "/workspace/FRESCO/./src/ebsynth/blender/guide.py", line 96, in get_cmd
    warped_img = flow_calc.warp(prev_img, self.flows[i - 1],
  File "/workspace/FRESCO/./src/ebsynth/flow/flow_utils.py", line 230, in warp
    if len(img.shape) == 2:
AttributeError: 'NoneType' object has no attribute 'shape'
[ WARN:0@117.473] global loadsave.cpp:248 findDecoder imread_('output/dog/out_23/0024.jpg'): can't open/read file: check file path/integrity
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/workspace/FRESCO/video_blend.py", line 111, in process_sequences
    process_one_sequence(i, video_sequence)
  File "/workspace/FRESCO/video_blend.py", line 98, in process_one_sequence
    cmd += ' ' + g.get_cmd(j, w)
  File "/workspace/FRESCO/./src/ebsynth/blender/guide.py", line 96, in get_cmd
    warped_img = flow_calc.warp(prev_img, self.flows[i - 1],
  File "/workspace/FRESCO/./src/ebsynth/flow/flow_utils.py", line 230, in warp
    if len(img.shape) == 2:
AttributeError: 'NoneType' object has no attribute 'shape'
[ WARN:0@118.020] global loadsave.cpp:248 findDecoder imread_('output/dog/out_72/0073.jpg'): can't open/read file: check file path/integrity
Process Process-4:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/workspace/FRESCO/video_blend.py", line 111, in process_sequences
    process_one_sequence(i, video_sequence)
  File "/workspace/FRESCO/video_blend.py", line 98, in process_one_sequence
    cmd += ' ' + g.get_cmd(j, w)
  File "/workspace/FRESCO/./src/ebsynth/blender/guide.py", line 96, in get_cmd
    warped_img = flow_calc.warp(prev_img, self.flows[i - 1],
  File "/workspace/FRESCO/./src/ebsynth/flow/flow_utils.py", line 230, in warp
    if len(img.shape) == 2:
AttributeError: 'NoneType' object has no attribute 'shape'
ebsynth: 118.52607154846191
[ WARN:0@119.641] global loadsave.cpp:248 findDecoder imread_('output/dog/out_0/0001.jpg'): can't open/read file: check file path/integrity
[ WARN:0@119.641] global loadsave.cpp:248 findDecoder imread_('output/dog/out_0/0002.jpg'): can't open/read file: check file path/integrity
[ WARN:0@119.641] global loadsave.cpp:248 findDecoder imread_('output/dog/out_0/0003.jpg'): can't open/read file: check file path/integrity
[ WARN:0@119.641] global loadsave.cpp:248 findDecoder imread_('output/dog/out_0/0004.jpg'): can't open/read file: check file path/integrity
[ WARN:0@119.641] global loadsave.cpp:248 findDecoder imread_('output/dog/out_0/0005.jpg'): can't open/read file: check file path/integrity
[ WARN:0@119.641] global loadsave.cpp:248 findDecoder imread_('output/dog/out_0/0006.jpg'): can't open/read file: check file path/integrity
[ WARN:0@119.641] global loadsave.cpp:248 findDecoder imread_('output/dog/out_0/0007.jpg'): can't open/read file: check file path/integrity
[ WARN:0@119.641] global loadsave.cpp:248 findDecoder imread_('output/dog/out_0/0008.jpg'): can't open/read file: check file path/integrity
[ WARN:0@119.641] global loadsave.cpp:248 findDecoder imread_('output/dog/out_0/0009.jpg'): can't open/read file: check file path/integrity
[ WARN:0@119.641] global loadsave.cpp:248 findDecoder imread_('output/dog/out_0/0010.jpg'): can't open/read file: check file path/integrity
[ WARN:0@119.641] global loadsave.cpp:248 findDecoder imread_('output/dog/out_11/0011.jpg'): can't open/read file: check file path/integrity
[ WARN:0@119.641] global loadsave.cpp:248 findDecoder imread_('output/dog/out_11/0001.jpg'): can't open/read file: check file path/integrity
[ WARN:0@119.641] global loadsave.cpp:248 findDecoder imread_('output/dog/out_11/0002.jpg'): can't open/read file: check file path/integrity
[ WARN:0@119.641] global loadsave.cpp:248 findDecoder imread_('output/dog/out_11/0003.jpg'): can't open/read file: check file path/integrity
[ WARN:0@119.641] global loadsave.cpp:248 findDecoder imread_('output/dog/out_11/0004.jpg'): can't open/read file: check file path/integrity
[ WARN:0@119.641] global loadsave.cpp:248 findDecoder imread_('output/dog/out_11/0005.jpg'): can't open/read file: check file path/integrity
[ WARN:0@119.641] global loadsave.cpp:248 findDecoder imread_('output/dog/out_11/0006.jpg'): can't open/read file: check file path/integrity
[ WARN:0@119.641] global loadsave.cpp:248 findDecoder imread_('output/dog/out_11/0007.jpg'): can't open/read file: check file path/integrity
[ WARN:0@119.641] global loadsave.cpp:248 findDecoder imread_('output/dog/out_11/0008.jpg'): can't open/read file: check file path/integrity
[ WARN:0@119.641] global loadsave.cpp:248 findDecoder imread_('output/dog/out_11/0009.jpg'): can't open/read file: check file path/integrity
[ WARN:0@119.641] global loadsave.cpp:248 findDecoder imread_('output/dog/out_11/0010.jpg'): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "/workspace/FRESCO/video_blend.py", line 308, in <module>
    main(args)
  File "/workspace/FRESCO/video_blend.py", line 268, in main
    process_seq(video_sequence, i, blend_histogram, blend_gradient)
  File "/workspace/FRESCO/video_blend.py", line 200, in process_seq
    dist1s.append(load_error(bin_a, img_shape))
  File "/workspace/FRESCO/video_blend.py", line 161, in load_error
    with open(bin_path, 'rb') as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'output/dog/out_0/0001.bin'
Traceback (most recent call last):
  File "/workspace/FRESCO/venv/lib/python3.10/site-packages/gradio/queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "/workspace/FRESCO/venv/lib/python3.10/site-packages/gradio/route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "/workspace/FRESCO/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1440, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/workspace/FRESCO/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1341, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/workspace/FRESCO/venv/lib/python3.10/site-packages/gradio/components/video.py", line 281, in postprocess
    processed_files = (self._format_video(y), None)
  File "/workspace/FRESCO/venv/lib/python3.10/site-packages/gradio/components/video.py", line 355, in _format_video
    video = self.make_temp_copy_if_needed(video)
  File "/workspace/FRESCO/venv/lib/python3.10/site-packages/gradio/components/base.py", line 226, in make_temp_copy_if_needed
    temp_dir = self.hash_file(file_path)
  File "/workspace/FRESCO/venv/lib/python3.10/site-packages/gradio/components/base.py", line 190, in hash_file
    with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'output/dog/blend.mp4'```

**Comment by williamyang1991** [comment]
Please refer to the issues and solutions here
https://github.com/williamyang1991/Rerender_A_Video#issues
![image](https://github.com/williamyang1991/FRESCO/assets/18130694/59f28e3a-7379-4ba0-95c5-2a8adb65fcd4)

**Comment by efwfe** [comment]
> Reference in ne

Try this `chmod a+x ./src/ebsynth/deps/ebsynth/bin/ebsynth`.

**Comment by karthikg-09** [comment]
> > Reference in ne
> 
> Try this `chmod a+x ./src/ebsynth/deps/ebsynth/bin/ebsynth`.
this fixed the issue thank you
