### ISSUE TITLE
 imageio version?

### ISSUE THREAD

**Issue by Jayden1818** [williamyang1991/FRESCO#15]
Traceback (most recent call last):
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\utils.py", line 650, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Desktop\FRESCO\webUI.py", line 312, in process1
    writer.append_data(curImg)
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\imageio\core\format.py", line 590, in append_data
    return self._append_data(im, total_meta)
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\imageio\plugins\ffmpeg.py", line 587, in _append_data
    self._initialize()
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\imageio\plugins\ffmpeg.py", line 630, in _initialize
    self._write_gen = self._ffmpeg_api.write_frames(
TypeError: write_frames() got an unexpected keyword argument 'audio_path'

**Comment by williamyang1991** [comment]
My imageio's version is 2.34.0

**Comment by Jayden1818** [comment]
> 我的imageio的版本是2.34.0

Thank you

pip install --upgrade imageio-ffmpeg
pip install --upgrade imageio
