### ISSUE TITLE
TypeError: Video.__init__() got an unexpected keyword argument 'source'

### ISSUE THREAD

**Issue by cvespaz** [williamyang1991/FRESCO#22]
TypeError: Video.__init__() got an unexpected keyword argument 'source'

cannot get past this error for webui, thank you for your time

**Comment by cvespaz** [comment]
nvm, thank you- installing the correct version of gradio fixed it.

**Comment by cvespaz** [comment]
now getting this after render runs:     
Traceback (most recent call last):
  File "C:\Users\chris\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\Users\chris\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\chris\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "C:\Users\chris\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\chris\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\to_thread.py", line 49, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\chris\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 2103, in run_sync_in_worker_thread
    return await future
  File "C:\Users\chris\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 823, in run
    result = context.run(func, *args)
  File "C:\Users\chris\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\utils.py", line 650, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\chris\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\chris\fresco\FRESCO\webUI.py", line 159, in process
    keypath = process1(*args)
  File "C:\Users\chris\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\chris\fresco\FRESCO\webUI.py", line 312, in process1
    writer.append_data(curImg)
  File "C:\Users\chris\AppData\Local\Programs\Python\Python310\lib\site-packages\imageio\v2.py", line 226, in append_data
    return self.instance.write(im, **self.write_args)
  File "C:\Users\chris\AppData\Local\Programs\Python\Python310\lib\site-packages\imageio\plugins\pyav.py", line 632, in write
    self.init_video_stream(codec, fps=fps, pixel_format=out_pixel_format)
  File "C:\Users\chris\AppData\Local\Programs\Python\Python310\lib\site-packages\imageio\plugins\pyav.py", line 836, in init_video_stream
    stream = self._container.add_stream(codec, fps)
  File "av\\container\\output.pyx", line 63, in av.container.output.OutputContainer.add_stream
ValueError: needs one of codec_name or template

**Comment by williamyang1991** [comment]
https://github.com/williamyang1991/FRESCO/issues/15#issuecomment-2011390089
Update your imageio?
