### ISSUE TITLE
run webUI.py with a 3 seconds video of 1280x720, got Error

### ISSUE THREAD

**Issue by bingjiw** [williamyang1991/FRESCO#29]
Running on local URL:  http://127.0.0.1:7860/
Running on public URL: https://26363563e97e3055dc.gradio.live/

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)
/usr/local/lib/python3.10/dist-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3526.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
100% 15/15 [01:10<00:00,  4.71s/it]
100% 15/15 [00:45<00:00,  3.01s/it]
python video_blend.py output/3 seconds --key keys --key_ind 0 12 18 27 32 52 57 64 74 79 90  --output output/3 seconds/blend.mp4 --fps 30 --n_proc 4 -ps
usage: video_blend.py [-h] [--output OUTPUT] [--fps FPS] [--key_ind KEY_IND [KEY_IND ...]]
                      [--key KEY] [--n_proc N_PROC] [-ps] [-ne] [-tmp]
                      name
video_blend.py: error: unrecognized arguments: seconds seconds/blend.mp4
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1440, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1341, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/usr/local/lib/python3.10/dist-packages/gradio/components/video.py", line 281, in postprocess
    processed_files = (self._format_video(y), None)
  File "/usr/local/lib/python3.10/dist-packages/gradio/components/video.py", line 355, in _format_video
    video = self.make_temp_copy_if_needed(video)
  File "/usr/local/lib/python3.10/dist-packages/gradio/components/base.py", line 226, in make_temp_copy_if_needed
    temp_dir = self.hash_file(file_path)
  File "/usr/local/lib/python3.10/dist-packages/gradio/components/base.py", line 190, in hash_file
    with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'output/3 seconds/blend.mp4'

**Comment by williamyang1991** [comment]
No space in your path.

Change `3 seconds` to `3_seconds`
