### ISSUE TITLE
[Run Key Frames] sucess, but [Run Propagation (Ebsynth)] failed: FileNotFoundError: [Errno 2] No such file or directory: 'output/480x480/blend.mp4'

### ISSUE THREAD

**Issue by bingjiw** [williamyang1991/FRESCO#30]
<img width="1440" alt="截屏2024-03-24 14 46 51" src="https://github.com/williamyang1991/FRESCO/assets/20619102/849c1aae-404f-41ce-9d1b-cc163ece510b">

Running on local URL:  http://127.0.0.1:7860/
Running on public URL: https://26363563e97e3055dc.gradio.live/

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)
/usr/local/lib/python3.10/dist-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3526.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
100% 15/15 [01:10<00:00,  4.71s/it]
100% 15/15 [00:45<00:00,  3.01s/it]
python video_blend.py output/3 seconds --key keys --key_ind 0 12 18 27 32 52 57 64 74 79 90  --output output/3 seconds/blend.mp4 --fps 30 --n_proc 4 -ps
usage: video_blend.py [-h] [--output OUTPUT] [--fps FPS] [--key_ind KEY_IND [KEY_IND ...]]
                      [--key KEY] [--n_proc N_PROC] [-ps] [-ne] [-tmp]
                      name
video_blend.py: error: unrecognized arguments: seconds seconds/blend.mp4
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1440, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1341, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/usr/local/lib/python3.10/dist-packages/gradio/components/video.py", line 281, in postprocess
    processed_files = (self._format_video(y), None)
  File "/usr/local/lib/python3.10/dist-packages/gradio/components/video.py", line 355, in _format_video
    video = self.make_temp_copy_if_needed(video)
  File "/usr/local/lib/python3.10/dist-packages/gradio/components/base.py", line 226, in make_temp_copy_if_needed
    temp_dir = self.hash_file(file_path)
  File "/usr/local/lib/python3.10/dist-packages/gradio/components/base.py", line 190, in hash_file
    with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'output/3 seconds/blend.mp4'
/content/drive/MyDrive/video_gen/FRESCO/src/free_lunch_utils.py:38: UserWarning: ComplexHalf support is experimental and many operators don't support it yet. (Triggered internally at ../aten/src/ATen/EmptyTensor.cpp:31.)
  x_freq = fft.fftn(x, dim=(-2, -1))
100% 15/15 [00:29<00:00,  1.96s/it]
100% 15/15 [00:19<00:00,  1.32s/it]
python video_blend.py output/480x480 --key keys --key_ind 0 12 18 27 32 52 57 64 74 79 90  --output output/480x480/blend.mp4 --fps 30 --n_proc 4 -ps
/usr/local/lib/python3.10/dist-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3526.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/usr/local/lib/python3.10/dist-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3526.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/usr/local/lib/python3.10/dist-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3526.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/usr/local/lib/python3.10/dist-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3526.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
[ WARN:0@5.889] global loadsave.cpp:248 findDecoder imread_('output/480x480/out_74/0075.jpg'): can't open/read file: check file path/integrity
Process Process-4:
[ WARN:0@5.900] global loadsave.cpp:248 findDecoder imread_('output/480x480/out_57/0058.jpg'): can't open/read file: check file path/integrity
Process Process-3:
[ WARN:0@5.981] global loadsave.cpp:248 findDecoder imread_('output/480x480/out_27/0028.jpg'): can't open/read file: check file path/integrity
Process Process-2:
[ WARN:0@6.350] global loadsave.cpp:248 findDecoder imread_('output/480x480/out_0/0001.jpg'): can't open/read file: check file path/integrity
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/MyDrive/video_gen/FRESCO/video_blend.py", line 111, in process_sequences
    process_one_sequence(i, video_sequence)
  File "/content/drive/MyDrive/video_gen/FRESCO/video_blend.py", line 98, in process_one_sequence
    cmd += ' ' + g.get_cmd(j, w)
  File "/content/drive/MyDrive/video_gen/FRESCO/./src/ebsynth/blender/guide.py", line 96, in get_cmd
    warped_img = flow_calc.warp(prev_img, self.flows[i - 1],
  File "/content/drive/MyDrive/video_gen/FRESCO/./src/ebsynth/flow/flow_utils.py", line 230, in warp
    if len(img.shape) == 2:
AttributeError: 'NoneType' object has no attribute 'shape'
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/MyDrive/video_gen/FRESCO/video_blend.py", line 111, in process_sequences
    process_one_sequence(i, video_sequence)
  File "/content/drive/MyDrive/video_gen/FRESCO/video_blend.py", line 98, in process_one_sequence
    cmd += ' ' + g.get_cmd(j, w)
  File "/content/drive/MyDrive/video_gen/FRESCO/./src/ebsynth/blender/guide.py", line 96, in get_cmd
    warped_img = flow_calc.warp(prev_img, self.flows[i - 1],
  File "/content/drive/MyDrive/video_gen/FRESCO/./src/ebsynth/flow/flow_utils.py", line 230, in warp
    if len(img.shape) == 2:
AttributeError: 'NoneType' object has no attribute 'shape'
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/MyDrive/video_gen/FRESCO/video_blend.py", line 111, in process_sequences
    process_one_sequence(i, video_sequence)
  File "/content/drive/MyDrive/video_gen/FRESCO/video_blend.py", line 98, in process_one_sequence
    cmd += ' ' + g.get_cmd(j, w)
  File "/content/drive/MyDrive/video_gen/FRESCO/./src/ebsynth/blender/guide.py", line 96, in get_cmd
    warped_img = flow_calc.warp(prev_img, self.flows[i - 1],
  File "/content/drive/MyDrive/video_gen/FRESCO/./src/ebsynth/flow/flow_utils.py", line 230, in warp
    if len(img.shape) == 2:
AttributeError: 'NoneType' object has no attribute 'shape'
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/MyDrive/video_gen/FRESCO/video_blend.py", line 111, in process_sequences
    process_one_sequence(i, video_sequence)
  File "/content/drive/MyDrive/video_gen/FRESCO/video_blend.py", line 98, in process_one_sequence
    cmd += ' ' + g.get_cmd(j, w)
  File "/content/drive/MyDrive/video_gen/FRESCO/./src/ebsynth/blender/guide.py", line 96, in get_cmd
    warped_img = flow_calc.warp(prev_img, self.flows[i - 1],
  File "/content/drive/MyDrive/video_gen/FRESCO/./src/ebsynth/flow/flow_utils.py", line 230, in warp
    if len(img.shape) == 2:
AttributeError: 'NoneType' object has no attribute 'shape'
ebsynth: 8.934192419052124
[ WARN:0@11.051] global loadsave.cpp:248 findDecoder imread_('output/480x480/out_0/0001.jpg'): can't open/read file: check file path/integrity
[ WARN:0@11.052] global loadsave.cpp:248 findDecoder imread_('output/480x480/out_0/0002.jpg'): can't open/read file: check file path/integrity
[ WARN:0@11.052] global loadsave.cpp:248 findDecoder imread_('output/480x480/out_0/0003.jpg'): can't open/read file: check file path/integrity
[ WARN:0@11.052] global loadsave.cpp:248 findDecoder imread_('output/480x480/out_0/0004.jpg'): can't open/read file: check file path/integrity
[ WARN:0@11.052] global loadsave.cpp:248 findDecoder imread_('output/480x480/out_0/0005.jpg'): can't open/read file: check file path/integrity
[ WARN:0@11.052] global loadsave.cpp:248 findDecoder imread_('output/480x480/out_0/0006.jpg'): can't open/read file: check file path/integrity
[ WARN:0@11.052] global loadsave.cpp:248 findDecoder imread_('output/480x480/out_0/0007.jpg'): can't open/read file: check file path/integrity
[ WARN:0@11.052] global loadsave.cpp:248 findDecoder imread_('output/480x480/out_0/0008.jpg'): can't open/read file: check file path/integrity
[ WARN:0@11.052] global loadsave.cpp:248 findDecoder imread_('output/480x480/out_0/0009.jpg'): can't open/read file: check file path/integrity
[ WARN:0@11.052] global loadsave.cpp:248 findDecoder imread_('output/480x480/out_0/0010.jpg'): can't open/read file: check file path/integrity
[ WARN:0@11.053] global loadsave.cpp:248 findDecoder imread_('output/480x480/out_0/0011.jpg'): can't open/read file: check file path/integrity
[ WARN:0@11.053] global loadsave.cpp:248 findDecoder imread_('output/480x480/out_12/0012.jpg'): can't open/read file: check file path/integrity
[ WARN:0@11.053] global loadsave.cpp:248 findDecoder imread_('output/480x480/out_12/0001.jpg'): can't open/read file: check file path/integrity
[ WARN:0@11.053] global loadsave.cpp:248 findDecoder imread_('output/480x480/out_12/0002.jpg'): can't open/read file: check file path/integrity
[ WARN:0@11.053] global loadsave.cpp:248 findDecoder imread_('output/480x480/out_12/0003.jpg'): can't open/read file: check file path/integrity
[ WARN:0@11.053] global loadsave.cpp:248 findDecoder imread_('output/480x480/out_12/0004.jpg'): can't open/read file: check file path/integrity
[ WARN:0@11.053] global loadsave.cpp:248 findDecoder imread_('output/480x480/out_12/0005.jpg'): can't open/read file: check file path/integrity
[ WARN:0@11.053] global loadsave.cpp:248 findDecoder imread_('output/480x480/out_12/0006.jpg'): can't open/read file: check file path/integrity
[ WARN:0@11.054] global loadsave.cpp:248 findDecoder imread_('output/480x480/out_12/0007.jpg'): can't open/read file: check file path/integrity
[ WARN:0@11.054] global loadsave.cpp:248 findDecoder imread_('output/480x480/out_12/0008.jpg'): can't open/read file: check file path/integrity
[ WARN:0@11.054] global loadsave.cpp:248 findDecoder imread_('output/480x480/out_12/0009.jpg'): can't open/read file: check file path/integrity
[ WARN:0@11.054] global loadsave.cpp:248 findDecoder imread_('output/480x480/out_12/0010.jpg'): can't open/read file: check file path/integrity
[ WARN:0@11.054] global loadsave.cpp:248 findDecoder imread_('output/480x480/out_12/0011.jpg'): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "/content/drive/MyDrive/video_gen/FRESCO/video_blend.py", line 308, in <module>
    main(args)
  File "/content/drive/MyDrive/video_gen/FRESCO/video_blend.py", line 268, in main
    process_seq(video_sequence, i, blend_histogram, blend_gradient)
  File "/content/drive/MyDrive/video_gen/FRESCO/video_blend.py", line 200, in process_seq
    dist1s.append(load_error(bin_a, img_shape))
  File "/content/drive/MyDrive/video_gen/FRESCO/video_blend.py", line 161, in load_error
    with open(bin_path, 'rb') as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'output/480x480/out_0/0001.bin'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1440, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1341, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/usr/local/lib/python3.10/dist-packages/gradio/components/video.py", line 281, in postprocess
    processed_files = (self._format_video(y), None)
  File "/usr/local/lib/python3.10/dist-packages/gradio/components/video.py", line 355, in _format_video
    video = self.make_temp_copy_if_needed(video)
  File "/usr/local/lib/python3.10/dist-packages/gradio/components/base.py", line 226, in make_temp_copy_if_needed
    temp_dir = self.hash_file(file_path)
  File "/usr/local/lib/python3.10/dist-packages/gradio/components/base.py", line 190, in hash_file
    with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'output/480x480/blend.mp4'

**Comment by williamyang1991** [comment]
Turn on the log by setting OPEN_EBSYNTH_LOG = True
And check whether you give the execute permission of ebsynth

https://github.com/williamyang1991/FRESCO/issues/26#issuecomment-2016438310

https://github.com/williamyang1991/FRESCO/issues/26#issuecomment-2016506984

https://github.com/williamyang1991/FRESCO/issues/26#issuecomment-2016515312
